# Generated by Django 5.0.2 on 2024-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=38)),
                ('fileField', models.FileField(upload_to='')),
                ('allowed', models.JSONField()),
            ],
        ),
    ]
