# Generated by Django 5.0.2 on 2024-07-30 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=12, null=True)),
                ('fileField', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('Expiration_date', models.DateTimeField(default=datetime.datetime(2024, 7, 31, 16, 51, 26, 942131))),
            ],
        ),
    ]
