# Generated by Django 5.0.2 on 2024-07-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
    ]
