# Generated by Django 5.0.2 on 2024-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_remove_file_allowed_remove_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileField',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
