# Generated by Django 5.0.2 on 2024-07-30 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_file_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 17, 15, 27, 406578)),
        ),
    ]
